name: Update database

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

permissions:
  contents: write

jobs:
  Update_json:
    env:
      API_AUTH_TOKEN: ${{ secrets.API_TOKEN }}
      BINARIES_PATH: ./zig-out/bin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0
      - name: Build binaries
        run: zig build --release=fast
      - name: Run all tasks in parallel
        run: |
          $BINARIES_PATH/databaseCompiler > ./database/main.json &
          $BINARIES_PATH/databaseCompiler2 > ./database/programs.json &
          $BINARIES_PATH/repoListCompressor web > ./database/web.json &
          $BINARIES_PATH/repoListCompressor gui > ./database/gui.json &
          $BINARIES_PATH/repoListCompressor games > ./database/games.json &
          $BINARIES_PATH/codeberg > ./database/codebergPrograms.json &
          $BINARIES_PATH/gitlab > ./database/gitlabPrograms.json &
          wait
      - name: Create Deep Search Database
        run: $BINARIES_PATH/createDeepSearchDB > ./database/deepSearchData.json
      - name: Config email
        run: git config --global user.name "Github Actions" && git config --global user.email "github-actions@users.noreply.github.com"

      - name: Git add
        run: git add .

      - name: Commit database
        run: git commit -m 'Updated database'

      - name: Push changes
        run: git push
