name: Database Creator

on:
  workflow_run:
    workflows: ["Project Builder"]
    types:
      - completed
  schedule:
    - cron: 0 * * * * # Runs at the start of every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_database:
    runs-on: ubuntu-latest
    steps:
      - name: Download binary
        run: wget -O ZigistryBackend https://github.com/Zigistry/ZigistryNewAndImprovedBackendDevelopment/releases/download/database/ZigistryBackend

      - name: Give binary execution permissions
        run: chmod +x ZigistryBackend

      - name: Build database.json
        env:
          GH_API_KEY: ${{ secrets.GITHUB_TOKEN }}
          CB_API_KEY: ${{ secrets.CB_API_KEY }}
        run: ./ZigistryBackend

      - name: database.json upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload database database.json --clobber

  update_readme_database:
    runs-on: ubuntu-latest
    steps:
      - name: Download binary
        run: wget -O search_preparer https://github.com/Zigistry/ZigistryNewAndImprovedBackendDevelopment/releases/download/database/search_preparer

      - name: Give binary execution permissions
        run: chmod +x search_preparer

      - name: Update readme_database
        run: ./search_preparer

      - name: search_data.json upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload database search_data.json --clobber
