name: index safe repos workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "30 4 * * *"

permissions:
  contents: read

jobs:
  run_index_safe_repos:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    env:
      GH_API_KEY: ${{ secrets.GITHUB_TOKEN }}
      CB_API_KEY: ${{ secrets.CODEBERG_TOKEN }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - name: Download index-safe-repos binary
        run: wget -O index-safe-repos https://github.com/Zigistry/database/releases/download/executables/index-safe-repos

      - name: Make binary executable
        run: chmod +x ./index-safe-repos

      - name: Run index-safe-repos
        run: ./index-safe-repos
