on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 * * * * # Runs at the start of every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_database:
    runs-on: ubuntu-latest

    # Got to know this from: https://github.com/marketplace/actions/setup-git-config
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Rust installation
        uses: dtolnay/rust-toolchain@stable

      - name: Build repo
        run: cargo build --release

      - name: Run
        env:
          GH_API_KEY: ${{ secrets.GITHUB_TOKEN }}
          CB_API_KEY: ${{ secrets.CB_API_KEY }}
        run: ./target/release/ZigistryBackend > ./database.json

      - name: database.json upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload database database.json --clobber

  update_readme_database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: installing zig
        uses: mlugg/setup-zig@v2

      - name: Update readme_database
        run: |
          zig build-exe ./src/search_preparer.zig -O ReleaseSafe -lc
          ./search_preparer

      - name: search_data.json upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload database search_data.json --clobber
